version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "4000:4000"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  nextjs-ui:
    build:
      context: ./photo-uploader
    ports:
      - "3000:3000"
    container_name: nextjs-ui
    stdin_open: true
    volumes:
       - ./photo-uploader:/usr/src/app/photo-uploader
       - /usr/src/app/photo-uploader/node_modules