import { PhotoDetails } from '@/components/PhotoDetails';
import Head from 'next/head';

export default function PhotoPage() {
  return (
    <>
      <Head>
        <title>Photo Page</title>
        <meta name="description" content="Generated by Mohd Makki" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PhotoDetails />
    </>
  );
}
