import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Heading } from '@chakra-ui/react'
import { HomePage } from '@/components/HomePage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Photo Uploader</title>
        <meta name="description" content="Generated by Mohd Makki" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  )
}
